# Generated by Django 5.2.4 on 2025-08-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0002_cosmetic'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetic',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
