# Generated by Django 5.2.4 on 2025-08-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0003_cosmetic_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logincosmetic',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
